### ISSUE TITLE
How do you build/run this?

### ISSUE THREAD

**Issue by oziphantom** [martinpiper/BDD6502#1]
The readme mentions BDD6502-1.0-SNAPSHOT-jar-with-dependencies.jar but when I download the files there are no jar files in it. 
From looking at the source files I guess there are also a bunch of other libs that are not linked so I need to download them and put them somewhere specific? If I'm to build it?

**Comment by martinpiper** [comment]
It's a Maven project. All you need to do to build it is build the pom.xml.

**Comment by oziphantom** [comment]
Ok so I need to install Marven ( The Apache one? ) and a JDK ( 7 or 8? ) , can't you just put a pre built file in?

**Comment by martinpiper** [comment]
I created a release package https://github.com/martinpiper/BDD6502/releases

**Comment by oziphantom** [comment]
Awesome, thanks. 

Seems the tool need Labels in ACME format which is different from the TASS format. 
TASS is "label = address" while 
ACME is "label = address; something else"
Does your tool look at the the "; something else" or can I just make a cmdline tool that appends "; dummy" to each line in the TASS label file to make it compatible?

**Comment by oziphantom** [comment]
For those that come after:
Yes just adding a "; dummy" on the end works, but also the ACME format puts things out as =$XXXX and not = $XXXX like TASS, the Java parser assumes that if it has a $ it will be the first character. So you need to patch the data to have =$ also remove and .var lines that TASS puts in. Also not the the ; must be right next to the end of the label string or it will also fail. 

I was able to use this windows host script file to do the conversion

```
set args = WScript.Arguments
num = args.Count

Dim objFS, objFile
Set objFS = CreateObject("Scripting.FileSystemObject")
Set objFile = objFS.CreateTextFile(args.Item(1),True)
Set inFile = objFS.OpenTextFile(args.Item(0))


Do While Not inFile.AtEndOfStream
     blah = inFile.ReadLine()
     blah = Replace(blah,"= $","=$")
     if( InStr(blah, "=") > 0 ) then objFile.WriteLine (blah & "; dummy")
Loop
```

To use it  cscript acmeToTass.vbs [in file] [out file]

Note needs the TASS labels format in its native NOT vice compatible
