### ISSUE TITLE
Can macros accept raw strings as parameters?

### ISSUE THREAD

**Issue by markjfisher** [martinpiper/BDD6502#16]
I'm trying to write something like:

```feature
      And I create file "build/tests/sio-patch" and patch machine with
      """
      ; stub SIOV
        icl "../../../../src/libs/atari/inc/os.inc"

        org SIOV
        ; copy t_v into the DBUF buffer (which is a pointer to real location of memory)
        mvw DBUFLO $80
        ldy #0
        mva t_v ($80),y
        rts

      ; an address for the test to write to. this is the stubbed value that will be written to by pointer at DBUF
      t_v dta 0

    """
```

I've got several macros working fine, but I'm struggling to write one for the above.

I've got this:

```feature
Given I create file "*" and patch machine with "*"
  When I create file "build/tests/$1.asm" with "$2"
   And I mads-compile "$1" from "build/tests/$1.asm"
   And I convert mads-labels file "build/tests/$1.lbl" to acme labels file "build/tests/$1.al"
   And I patch machine from obx file "build/tests/$1"
```

but when I run the feature I get an error saying there's no definition for the step:

```java
// You can implement missing steps with the snippets below:

@Given("^I create file \"([^\"]*)\" and patch machine with$")
public void i_create_file_and_patch_machine_with(String arg1, String arg2) throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}
```

so it doesn't seem to be matching the macro.

I've tried putting triple quotes around the macro's 2nd parameter, but still had same error.
I also tried joining the raw string in the Step itself onto the step line, like:

```
And I create file "build/tests/sio-patch" and patch machine with """
    ; stub SIOV
    // ...
```

but that threw an error parsing the feature.

EDIT: I've worked around it by using the " And I create file "build/tests/sio-patch.asm" with" step instead, but still wonder if there's a way to do it directly.
Thanks.

**Comment by martinpiper** [comment]
Yes they can, in this commit: :)

https://github.com/martinpiper/CukesPlus/commit/2117133139e990e166f00c92dbfdbe9e7ec0bb77#diff-071e0410df09295b8a24dbb7590aeebbcb00ac46c81dadef37fabe4070dae659R4

I've made the repo public now too...

Text block and table insertion into a specific point can be implemented by having a macro directive such as "<<<" or "<<< number of rows"
The number of rows can also be a resolved property based value. e.g. <<< ${test.insert.rows}

**Comment by markjfisher** [comment]
Wow, thankyou this is great news both on the change and being public. I'll look to moving over to this today.

**Comment by markjfisher** [comment]
> I've made the repo public now too...

Would you also consider using github to host your deployed repositories directly?

e.g. https://www.baeldung.com/maven-repo-github

That way, they can be used as gradle/maven dependencies directly in projects without users having to compile anything locally, they just point to BDD6502 and maven/gradle pulls in the dependencies directly.

It would mean you having to publish all 3 repos this way; ACEServer, CukesPlus, and BDD6502, but I think it's really worth the effort, as people would:
- get src linkage directly to the version they have a dependency on to use in IDE
- get feature contextural help in IntelliJ
- only need to include BDD6502
- easily be able to update as new versions are released by incrementing the version number
- wouldn't need to include instructions on building/deploying locally dependency libs

I've been using gradle since pre 1.0 days, so only having to have

```gradle
dependencies {
    implementation("github.com:martinpiper-bdd6502:1.0.1")
}
```
would be a huge win.

At the moment I have
```
dependencies {
    implementation(files("lib/BDD6502-1.0.9-SNAPSHOT-jar-with-dependencies.jar"))
}
```

and a huge jar in my repo

Making it public repo is a great step, but I have to go and fetch and locally compile ACEServer, and CukesPlus, which means my users will also have to do it.

I'm sure you probably know all this already, so this is just me asking really really nicely 🙏

**Comment by martinpiper** [comment]
All three repos are public:
https://github.com/martinpiper/ACEServer
https://github.com/martinpiper/CukesPlus
https://github.com/martinpiper/BDD6502

But the github package build and deploy config isn't that easy, so I'm not going to spend any time on trying to get it working. :)

**Comment by markjfisher** [comment]
Ok, thanks, I had to ask :)

**Comment by markjfisher** [comment]
ok, i had to have a go at this :)
I've forked your repo, and pushed a change to it that makes ACEServer available to gradle or maven with following:

```gradle
repositories {
    mavenCentral()
    maven("https://raw.githubusercontent.com/markjfisher/mary/master")
}

dependencies {
    implementation("net.fish:aceserver:0.0.12")
}
```
The commit I pushed is here:
https://github.com/markjfisher/ACEServer/commit/79277466864e85e8f07542cd4e792a7c8d07d8b3

Steps were:
- Create a github project called "mary" with just a README, and master branch - can be any name, mary is "MAven repositoRY" that I've seen used before. It's just a repo that will contain published repos that can be used as dependencies
- convert ACEServer project to gradle (I know this way better, and there's a plugin that does the repo things) by running
```shell
gradle init
```
- amend the project name from "ACEServer" to "aceserver" (github doesn't allow non-lower case names) in settings.gradle.kts
- add the 'magik' plugin to build.gradle.kts (https://github.com/elect86/magik)
- add a Personal Access Token (classic) to my github account, put it in "C:\users\my-user\.gradle\gradle.properties" file as per instructions for magik
- ensured versions and names were set how I want, and pushed latest changes to my fork
- ran "./gradlew publishMavenPublicationToGithubRepository"

This builds the whole application including sources (because of the `withSources()` in build.gradle.kts, and then pushes a copy of the jars md5s etc to your 'mary' repo.

You can see mine at https://github.com/markjfisher/mary

I practiced first on my "atari-utils" project and pushed that, then did ACEServer by copy/pasting the build script.

That's about it, once setup, you can just bump versions and run `./gradlew publishMavenPublicationToGithubRepository` again to publish new versions.

I did try using github repos how they suggested, but everyone would need a public key to access it, so went with the above magik plugin solution.

**Comment by martinpiper** [comment]
Thanks for that. but I don't really want to have to switch to gradle. :) Also I shouldn't have to make any local setting changes since it should be github running the build and deploy. It should be as simple as adding the correct "distributionManagement" section to the pom and creating the right action to build snapshots. But github is really bad at the correct documentation for this. All they need to do is hvae a bare bones working pom and workflow example, but they don't.

**Comment by martinpiper** [comment]
Searching shows many many issues like this...
https://stackoverflow.com/questions/57711558/deploy-to-github-package-registry-from-github-action

Docs...
https://github.com/marketplace/actions/action-maven-publish

**Comment by markjfisher** [comment]
> I don't really want to have to switch to gradle. :)

I thought it might be a stretch :) I see you have a lot of maven bits and pieces in your repo.

> But github is really bad at the correct documentation for this

After trawling through it for some hours myself I can only agree.
I had seen the workflows you'd commit to the project and wondered how close it was to working that way.

The issue I found when I did get a push to github package registry via gradle, (my first experiment before magik route) was that I needed to set credentials in my consuming application to access those resources that were published.

I couldn't (even on my own project) simply use github repo as a public resource, and found some articles pointing out that wasn't implemented (see below), so users would always need a token to download, which seemed pretty pointless to me. everything in the github docs seem to say you can change visibility and it should inherit from your repositories, but those settings were not there to change.

I thought it may need to target one of the "granular" repositories listed here: https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages#granular-permissions-for-userorganization-scoped-packages
but that list is not right for java deployments.

I found the magik plugin in the comments to this SO question (which also talked about packages not being public without tokens):
https://stackoverflow.com/questions/64419343/how-to-reference-public-github-packages-from-maven-project

very frustrating.

I've used nexus before for some public repos I published to get from maven (https://central.sonatype.com/search?smo=true&q=net.markjfisher) but it was a pain to setup, you need the domain yourself, the interface is slow, etc.

~~anyway, i'm going to temporarily publish all 3 repos in my forks, and merge in any changes you make to the core so I'm up to date, and at some point see if I can get the workflow working correctly so all the gradle stuff can be stripped out.~~

edit: i'm just going to build them to local repo and include instructions in my repos for my consumers as there just aren't enough people who will benefit my side from me publishing your repos publically.

I'd love to help get yours public eventually though if possible.

**Comment by martinpiper** [comment]
I've sent a request to github to clarify their docs with a very simple java maven example. Let's see what they say.
