### ISSUE TITLE
ST register checking seems to be broken

### ISSUE THREAD

**Issue by oziphantom** [martinpiper/BDD6502#2]
When testing the ST register state seems to pass no matter what

Then I expect register ST contain stN
  And I expect register ST contain stV
  And I expect register ST equal 0
  And I expect register ST equal stZ

Passes, even though there is no way all of them can be true.

**Comment by martinpiper** [comment]
Odd. What was the decimal or hex value of ST?

**Comment by martinpiper** [comment]
Tested this, it works?

Feature:  Maxchine state test

  This tests expected machine state

Scenario: Simple machine state test
  Given I have a simple 6502 system
  And I create file "test.a" with
  """
  !sal
  *=$400
  start
    lda #0
    php
    lda #12
    ldx #14
    ldy #17
    plp
    rts
  """
  And I run the command line: ..\C64\acme.exe -o test.prg --labeldump test.lbl -f cbm test.a
  And I load prg "test.prg"
  And I load labels "test.lbl"

  When I execute the procedure at start for no more than 100 instructions

  # Note how the label "start" is used below and correctly resolves to be $400 when checking memory
  Then I expect register A equal 12
  And I expect register X equal 14
  And I expect register Y equal 17
  # stC = 1
  # stZ = 2
  # stI = 4
  # stD = 8
  # stV = 64
  # stN = 128
  And I expect register ST equal stZ
  # Performs a logical bit set test
  And I expect register ST contain stZ
  And I expect register ST exclude stI


  Scenario: Simple machine state write test
    Given I have a simple 6502 system
    And I create file "test.a" with
  """
  !sal
  *=$400
  start
    sta $500
    stx $501
    sty $502
    php
    pla
    sta $503
    rts
  """
    And I run the command line: ..\C64\acme.exe -o test.prg --labeldump test.lbl -f cbm test.a
    And I load prg "test.prg"
    And I load labels "test.lbl"

    When I set register A to 1
    And I set register X to 2
    And I set register Y to 3
    And I set register ST to stZ
    And I execute the procedure at start for no more than 100 instructions

    # Note how the label "start" is used below and correctly resolves to be $400 when checking memory
    Then I expect to see $500 equal 1
    And I expect to see $501 equal 2
    And I expect to see $502 equal 3
    And I expect to see $503 contain stZ
    And I expect to see $503 equal $32


  Scenario: Machine status register tests
    Given I have a simple 6502 system

    When I set register ST to 0
    Then I expect register ST equal 0

    When I set register ST to 1
    Then I expect register ST equal stC

    When I set register ST to 2
    Then I expect register ST equal stZ

    When I set register ST to 4
    Then I expect register ST equal stI

    When I set register ST to 8
    Then I expect register ST equal stD

    When I set register ST to 64
    Then I expect register ST equal stV

    When I set register ST to 128
    Then I expect register ST equal stN

    When I set register ST to 128+64
    Then I expect register ST equal stN+stV
    Then I expect register ST contain stN+stV
    Then I expect register ST contain stN
    Then I expect register ST contain stV


    When I set register ST to 2+4
    Then I expect register ST contain stZ
    Then I expect register ST contain stI
    Then I expect register ST equal stI+stZ
    Then I expect register ST contain stI+stZ

**Comment by martinpiper** [comment]
Scenario: Machine status register tests
    Given I have a simple 6502 system

```
When I set register ST to 0
Then I expect register ST equal 0

When I set register ST to 1
Then I expect register ST equal stC

When I set register ST to 2
Then I expect register ST equal stZ

When I set register ST to 4
Then I expect register ST equal stI

When I set register ST to 8
Then I expect register ST equal stD

When I set register ST to 64
Then I expect register ST equal stV

When I set register ST to 128
Then I expect register ST equal stN

When I set register ST to 128+64
Then I expect register ST equal stN+stV
Then I expect register ST contain stN+stV
Then I expect register ST contain stN
Then I expect register ST contain stV


When I set register ST to 2+4
Then I expect register ST contain stZ
Then I expect register ST contain stI
Then I expect register ST equal stI+stZ
Then I expect register ST contain stI+stZ
```

**Comment by oziphantom** [comment]
It didn't give one, it just passed. 

Your test above is only checking to make sure it passes, you need to check a fail case and see that it fails. In that a test design to test a correct case for something that always passes will still pass. 

If if does fail then maybe it was a markup error that doesn't cause an error but causes the test to pass without being checked?

**Comment by martinpiper** [comment]
Yeah, I tried a few failing test cases just to be sure. They were then
removed from the scenario.
If you can reproduce let me know the register value and the failing steps.

**Comment by oziphantom** [comment]
Sadly the above is basically all I have left, as the original code has changed dramatically as has the test. So I will mark it as closed for now, and if I get another case in the future I will make a full state grab for forensics and open a new issue with it.
