### ISSUE TITLE
Feature Request : % parser

### ISSUE THREAD

**Issue by oziphantom** [martinpiper/BDD6502#3]
Can we have % as well as $. When testing bit patterns in compression or graphics writing, or emulating say the Joystick register DC00. Writing 21 for down and right is really easy to mess up and hard to read while doing %00010101 makes it a bit more obvious what you are testing.

**Comment by martinpiper** [comment]
Added % to use for binary values.

https://github.com/martinpiper/BDD6502/releases/tag/1.0.4

**Comment by martinpiper** [comment]
Scenario: Simple binary test code
    Given I have a simple 6502 system
    And I start writing memory at $400
    And I write the following hex bytes
      | 11 22 33 44 55 66 77 88 |

```
Then I expect to see $400 equal %00010001
And I expect to see $401 equal %00100010
And I expect to see $402 equal %00110011
And I expect to see $403 equal %01000100
And I expect to see $404 equal %01010101
And I expect to see $405 equal %01100110
And I expect to see $406 equal %01110111
And I expect to see $407 equal %10001000
```

**Comment by oziphantom** [comment]
Awesome thanks
