### ISSUE TITLE
Feature Request : Ability to check against a location in memory

### ISSUE THREAD

**Issue by oziphantom** [martinpiper/BDD6502#4]
Say you are making some code that looks up which X offset you want it to check, it reads in some data and then looks up a table. 
You either write the code to check the X or the Y register is the right offset - this is brittle and may not work as by the end of the function they might be restored to the value when passed in. 
You might also re-factor the code at some point and change your use of X and Y causing the test to fail

OR 

You check that A or the variable it writes contains the expected value that is currently in the table. Which again might change at some point causing the test to fail. 

So having a 
And I expect ZPTemp to contain the value in MyTable+6 
or
And I expect ZPTemp to contain the value (MyTable+6) <- might work better when part of an _Examples:_ table

would be nice.

**Comment by martinpiper** [comment]
Added syntax:

Given I set label <name> equal to <value>
Then I expect memory <value> to equal memory <value>

**Comment by martinpiper** [comment]
https://github.com/martinpiper/BDD6502/releases/tag/1.0.4

**Comment by martinpiper** [comment]
Scenario: Simple memory test code
    Given I have a simple 6502 system
    Given I set label foo equal to $400

```
When I start writing memory at $400
And I write the following hex bytes
  | 11 22 33 44 55 66 77 88 |
  | 11 22 33 44 55 66 77 88 |

Then I expect memory $400+0 to equal memory $400+8+0
Then I expect memory foo+1 to contain memory foo+8+1
Then I expect memory $400+0 to exclude memory foo+8+1
```

**Comment by oziphantom** [comment]
Awesome thanks
